
/**
 * DO NOT MODIFY THIS FILE!
 *
 * This file is generated by the salesforce-to-types plugin and
 * may be regenerated in the future. It is recommended to make
 * changes to that plugin then regenerate these files.
 *
 */

import { SObjectAttribute } from './sobject';
import { ID, ChildRecords, DateString, PhoneString } from './sobjectFieldTypes';

export interface Account extends SObjectAttribute<'Account'> {
  Name: string;
  BillingAddress: string //address;
  Phone: PhoneString;
  LastModifiedDate: DateString | null;
  ChildAccounts: ChildRecords<Account, 'Account'>;
  Cases: ChildRecords<Case, 'Case'>;
  Contacts: ChildRecords<Contact, 'Contact'>;
  // ...
};


export interface Contact extends SObjectAttribute<'Contact'> {
  AccountId: ID;
  Account: Account;
  LastName: string;
  FirstName: string;
  Phone: PhoneString;
  Cases: ChildRecords<Case, 'Case'>;
  // ...
};


export interface Opportunity extends SObjectAttribute<'Opportunity'> {
  Account: Account;
  Name: string;
  Description: string;
  Amount: number;
  Quotes__r: ChildRecords<Quote__c, 'Quote__c'>;
  // ...
};

type Case = any; 
type Quote__c = any; 